# Generated by Django 3.2.8 on 2021-11-09 18:31

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_alter_review_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=100, size=[200, 300], upload_to='book_covers'),
        ),
    ]
